import os
import numpy as np
import asciitable as at

def make_ar_atmos(exptime, rate, alpha_mag, n, atmlayers, nofroflo=False, atmtype=0, 
                  onelayer=False, dept=False, save=True, compare=False, 
                  ranseed=0.0, mini=False, hdf5=False):

    """
    ;; Srikar Srinath - 2014-05-07
    ;; Makes an n-layer frozen flow atmosphere with boiling sized for the
    ;; telescope parameters in the first few lines of the program
    ;; Inputs:
    ;;       exptime   - (float) exposure time in seconds
    ;;       rate      - (float) observation sampling rate in Hertz (usually 1500 Hz)
    ;;       alpha_mag - magnitude of autoregressive alpha parameter
    ;;                   (1 - alpha_mag) determines fraction of phase from
    ;;                   prior timestep that is "forgotten" e.g. 
    ;;                   alpha_mag = 0.9 implies 10% forgotten
    ;;                   set to an array for multi-layer atmosphere
    ;;       n         - number of subapertures across screen (not the
    ;;                   number of subapertures across the aperture, which
    ;;                   is less than this number)
    ;;        Flags:
    ;;        nofroflo - flag that gives a "boiling only" atmosphere
    ;;                   i.e. all frozen flow velocities set to 0
    ;;        atmtype  - atmosphere type flag for cdr_create_parameters
    ;;                   set to 0 by default for the standard n-layer
    ;;                   Cerro Pachon atmosphere. Allowed values are
    ;;                   15,2,25,3,4 which multiplies power by 1.5,2 etc.
    ;;        onelayer - flag to just use one  layer of atmsphere to speed
    ;;                   things up. [r0, vel, dir] for this layer set in
    ;;                   code below
    ;;        dept     - depiston and detilt the output and impose the
    ;;                   aperture
    ;;        save     - flag to save files with individual layer
    ;;                   phase, summed phase as seen by pupil and FT of
    ;;                   summed phase. Default format is FITS
    ;;        hdf5     - Save to HDF5 format instead
    ;;        compare  - compare RMS of AR phase with random phase screens
    ;;                   generated by other methods - screengen, pure
    ;;                   frozen flow, random uncorrelated. Only for use
    ;;                   with one layer case. 
    ;;        ranseed  - set to use preset random seed in code below. Allows
    ;;                   comparison between atmosphere realizations if
    ;;                   same (e.g. for different values of alpha_mag)
    ;; Outputs:
    ;;        phase    - FITS or HDF5 file with bign x bign x layers x timesteps
    """

        timesteps = exptime * rate
        r0 = 0.2 ; meters
        
        
    return
